# First, retrieve the most recent go version from the collection of go Docker images
FROM golang:1.23.1-alpine AS build

# Afterwards, create the working directory into the image
WORKDIR /app

# Copy all of the files over into the image
COPY . .

# Install all go dependcies, removing unnecessary ones, and adding necessary ones/
RUN go mod tidy

# Create the binary needed to run the go program.
RUN go build -o deploy .

# Second stage: Create a minimal image to run the Go app
FROM alpine:latest

# Copy the binary from the build stage to the final image
COPY --from=build /app/deploy .

# Expose the following port
EXPOSE 8080

CMD [ "/app/deploy" ]